### ISSUE TITLE
Add SEO Metadata (<meta tags): title, og, twitter, keywords

### ISSUE THREAD

**Issue by EliseiNicolae** [iosifnicolae2/radio-crestin.com#14]
<img width="208" alt="image" src="https://user-images.githubusercontent.com/43387542/194740894-ee9f681a-fa74-46a4-be71-35e8acd69dc9.png">

**Comment by iosifnicolae2** [comment]
Also, this task does a bit of SEO improvements: https://github.com/iosifnicolae2/radio-crestin.com/issues/12
