### ISSUE TITLE
[BUG] Notification player

### ISSUE THREAD

**Issue by iosifnicolae2** [iosifnicolae2/radio-crestin.com#18]
- [x] when the user stop the player from the notification bar, the player is really stoped and the user can watch Youtube videos without being interrupted
(this bug is only present on moblie)
- [x] add the functionality to return back to the previous station.
- [x] when you press stop from the notifications, you can start it again
- [x] sometimes the metadata is not showing in Notification Player.

https://user-images.githubusercontent.com/43387542/210205291-b618a166-e688-4bfe-82f6-0871bface4cc.MP4

**Comment by EliseiNicolae** [comment]
Updated.
