### ISSUE TITLE
Add logs (frontend + backend)

### ISSUE THREAD

**Issue by EliseiNicolae** [iosifnicolae2/radio-crestin.com#45]
Library: [sentry.io](https://docs.sentry.io/platforms/javascript/guides/nextjs/)

**Comment by EliseiNicolae** [comment]
Next 13 is not compatible with `sentry-wizard`

<img width="902" alt="image" src="https://user-images.githubusercontent.com/43387542/203942319-e38fb454-24a3-4e9c-a624-18582cc21e80.png">

Details: https://github.com/getsentry/sentry-javascript/issues/6290

- [ ] Downgrade the NEXT.JS version? Is this possible with a tool?

**Comment by lforst** [comment]
We'll release a new wizard version like really soon that will make this work.
